version: "3.8"
services:
  main:
    build: .
    ports:
      - "8080"
    restart: on-failure
    depends_on:
      - postgresql
    networks:
      - fullstack
    env_file:
      - .env
    # Starts up 2 replicas of the same image
    deploy:
      replicas: 2

  postgresql:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - fullstack

  nginx:
    image: nginx:latest
    # Connects the conf file of the container to the conf file in our folder
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # It will start up the nginx only when all api containers have started
    depends_on:
      - main
      - postgresql
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
      - "80:80"
    networks:
      - fullstack

  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - /Users/kevin/git/groot/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    links:
      - postgresql
    depends_on:
      - postgresql
      - main
      - nginx

networks:
  fullstack:
    driver: bridge