version: "3.8"
services:
  main:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgresql
    networks:
      - fullstack
    env_file:
      - .env

  postgresql:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - fullstack

  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - /Users/kevin/git/groot/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    links:
      - postgresql
    depends_on:
      - postgresql

networks:
  fullstack:
    driver: bridge