version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgresql
    networks:
      - fullstack

  postgresql:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge