name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call deployment webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          verbose: true
          verify_ssl: false
